version: "3.3"
services:
  react-app:
    build:
      context: .
    ports:
      - "1010:443"
    depends_on:
      - node-backend
      - mysql-db
    networks:
      - pinakastra-cloud_my-network
    volumes:
      - shared-data:/usr/share/nginx/html
      - ./ssl:/etc/nginx/ssl # Mount the SSL directory
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  
    restart: always

  node-backend:
    build:
      context: ./backend/db
    ports:
      - "5000:5000"
    depends_on:
      - mysql-db
    environment:
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PASSWORD=Likith@172323
      - DB_NAME=standalone
      - EMAIL_USER=pinakastra.join@gmail.com
      - EMAIL_PASS=sqei dbiv vxou ddsy
      - SESSION_SECRET=your-secret-key
    entrypoint: [ "/bin/sh", "-c", "./wait-for-it-script.sh mysql-db node server.js" ]
    volumes:
      - ./ssl:/etc/ssl # Mount the SSL directory
      - ./update-password.sh:/usr/src/app/update-password.sh
      - ./.env:/usr/src/app/.env
    networks:
      - pinakastra-cloud_my-network
    restart: always

volumes:
  mysql-data:
  shared-data:


networks:
  pinakastra-cloud_my-network:
    external: true
